#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations runes
python manage.py migrate
python manage.py migrate --database=runes_db runes
python manage.py runserver_plus 0.0.0.0:8000
