test:
  script:
  #- export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements/local.txt
  - python manage.py test

staging:
  type: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    # Run ssh-agent inside the build environment
    - ssh-agent -s
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_TOKEN" | tr -d '\r' | ssh-add - > /dev/null

  script:
    - ssh $DEPLOYMENT_SSH_CONNECTION
    - git pull
