# Generated by Django 2.0.2 on 2018-03-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'crosses',
            },
        ),
        migrations.CreateModel(
            name='CrossDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_certain', models.BooleanField(default=True)),
                ('cross', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='runes.Cross')),
            ],
            options={
                'db_table': 'cross_definitions',
            },
        ),
        migrations.CreateModel(
            name='CrossForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'cross_forms',
            },
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField()),
                ('direct_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'material_types',
            },
        ),
        migrations.CreateModel(
            name='MetaInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_location', models.TextField()),
                ('parish', models.TextField(blank=True)),
                ('district', models.TextField(blank=True)),
                ('municipality', models.TextField(blank=True)),
                ('current_location', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('original_site', models.TextField(blank=True)),
                ('present_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('present_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('parish_code', models.TextField(blank=True)),
                ('rune_type', models.TextField(blank=True)),
                ('dating', models.TextField(blank=True)),
                ('style', models.TextField(blank=True)),
                ('carver', models.TextField(blank=True)),
                ('material', models.TextField(blank=True)),
                ('objectInfo', models.TextField(blank=True)),
                ('additional', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('lost', models.BooleanField(default=False)),
                ('new_reading', models.BooleanField(default=False)),
                ('materialType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runes.MaterialType')),
            ],
            options={
                'db_table': 'meta_information',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_text', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'signatures',
            },
        ),
        migrations.CreateModel(
            name='SignatureMetaRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='runes.MetaInformation')),
            ],
        ),
        migrations.CreateModel(
            name='NormalisationNorse',
            fields=[
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='normalisation_norse', serialize=False, to='runes.Signature')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'normalisation_norse',
            },
        ),
        migrations.CreateModel(
            name='NormalisationScandinavian',
            fields=[
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='normalisation_scandinavian', serialize=False, to='runes.Signature')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'normalisation_scandinavian',
            },
        ),
        migrations.CreateModel(
            name='TranslationEnglish',
            fields=[
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='translation_english', serialize=False, to='runes.Signature')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'translation_english',
            },
        ),
        migrations.CreateModel(
            name='TransliteratedText',
            fields=[
                ('signature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transliteration', serialize=False, to='runes.Signature')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'transliterated_text',
            },
        ),
        migrations.AddField(
            model_name='signaturemetarelation',
            name='signature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='runes.Signature'),
        ),
        migrations.AddField(
            model_name='signature',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='runes.Signature'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runes.MaterialType'),
        ),
        migrations.AddField(
            model_name='imagelink',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='runes.MetaInformation'),
        ),
        migrations.AddField(
            model_name='crossdefinition',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runes.CrossForm'),
        ),
        migrations.AddField(
            model_name='cross',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosses', to='runes.MetaInformation'),
        ),
    ]
