# Generated by Django 2.0.2 on 2018-05-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cross",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "crosses",
            },
        ),
        migrations.CreateModel(
            name="CrossDefinition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_certain", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cross_definitions",
            },
        ),
        migrations.CreateModel(
            name="CrossForm",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("group_id", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "cross_forms",
            },
        ),
        migrations.CreateModel(
            name="ImageLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link_url", models.URLField()),
                ("direct_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaterialType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "material_types",
            },
        ),
        migrations.CreateModel(
            name="MetaInformation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("found_location", models.TextField()),
                ("parish", models.TextField(blank=True)),
                ("district", models.TextField(blank=True)),
                ("municipality", models.TextField(blank=True)),
                ("current_location", models.TextField(blank=True)),
                ("latitude", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("original_site", models.TextField(blank=True)),
                ("present_latitude", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("present_longitude", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("parish_code", models.TextField(blank=True)),
                ("rune_type", models.TextField(blank=True)),
                ("dating", models.TextField(blank=True)),
                ("style", models.TextField(blank=True)),
                ("carver", models.TextField(blank=True)),
                ("material", models.TextField(blank=True)),
                ("objectInfo", models.TextField(blank=True)),
                ("additional", models.TextField(blank=True)),
                ("reference", models.TextField(blank=True)),
                ("lost", models.BooleanField(default=False)),
                ("new_reading", models.BooleanField(default=False)),
                ("ornamental", models.BooleanField(default=False)),
                ("recent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "meta_information",
            },
        ),
        migrations.CreateModel(
            name="NameUsage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word_index", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalName",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("signature_text", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "signatures",
            },
        ),
        migrations.CreateModel(
            name="NormalisationNorse",
            fields=[
                ("value", models.TextField(blank=True)),
                ("search_value", models.TextField(blank=True)),
                (
                    "signature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="normalisation_norse",
                        serialize=False,
                        to="runes.Signature",
                    ),
                ),
            ],
            options={
                "db_table": "normalisation_norse",
            },
        ),
        migrations.CreateModel(
            name="NormalisationScandinavian",
            fields=[
                ("value", models.TextField(blank=True)),
                ("search_value", models.TextField(blank=True)),
                (
                    "signature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="normalisation_scandinavian",
                        serialize=False,
                        to="runes.Signature",
                    ),
                ),
            ],
            options={
                "db_table": "normalisation_scandinavian",
            },
        ),
        migrations.CreateModel(
            name="TranslationEnglish",
            fields=[
                ("value", models.TextField(blank=True)),
                ("search_value", models.TextField(blank=True)),
                (
                    "signature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="translation_english",
                        serialize=False,
                        to="runes.Signature",
                    ),
                ),
            ],
            options={
                "db_table": "translation_english",
            },
        ),
        migrations.CreateModel(
            name="TransliteratedText",
            fields=[
                ("value", models.TextField(blank=True)),
                ("search_value", models.TextField(blank=True)),
                (
                    "signature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="transliteration",
                        serialize=False,
                        to="runes.Signature",
                    ),
                ),
            ],
            options={
                "db_table": "transliterated_text",
            },
        ),
        migrations.AddField(
            model_name="signature",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="runes.Signature",
            ),
        ),
        migrations.AddIndex(
            model_name="personalname",
            index=models.Index(fields=["value"], name="runes_perso_value_857aa6_idx"),
        ),
        migrations.AddField(
            model_name="nameusage",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="usage", to="runes.PersonalName"
            ),
        ),
        migrations.AddField(
            model_name="nameusage",
            name="signature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="personal_names", to="runes.Signature"
            ),
        ),
        migrations.AddField(
            model_name="metainformation",
            name="materialType",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="runes.MaterialType"
            ),
        ),
        migrations.AddField(
            model_name="metainformation",
            name="signature",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="meta", to="runes.Signature"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="runes.MaterialType"),
        ),
        migrations.AddField(
            model_name="imagelink",
            name="meta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="images", to="runes.MetaInformation"
            ),
        ),
        migrations.AddField(
            model_name="crossdefinition",
            name="cross",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="forms", to="runes.Cross"
            ),
        ),
        migrations.AddField(
            model_name="crossdefinition",
            name="form",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="runes.CrossForm"),
        ),
        migrations.AddField(
            model_name="cross",
            name="meta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="crosses", to="runes.MetaInformation"
            ),
        ),
        migrations.AddIndex(
            model_name="transliteratedtext",
            index=models.Index(fields=["search_value"], name="translitera_search__004559_idx"),
        ),
        migrations.AddIndex(
            model_name="translationenglish",
            index=models.Index(fields=["search_value"], name="translation_search__d77654_idx"),
        ),
        migrations.AddIndex(
            model_name="signature",
            index=models.Index(fields=["signature_text"], name="signatures_signatu_b77f7b_idx"),
        ),
        migrations.AddIndex(
            model_name="normalisationscandinavian",
            index=models.Index(fields=["search_value"], name="normalisati_search__0c0d01_idx"),
        ),
        migrations.AddIndex(
            model_name="normalisationnorse",
            index=models.Index(fields=["search_value"], name="normalisati_search__82a5f9_idx"),
        ),
        migrations.AddIndex(
            model_name="metainformation",
            index=models.Index(fields=["found_location"], name="meta_inform_found_l_a80996_idx"),
        ),
        migrations.AddIndex(
            model_name="metainformation",
            index=models.Index(fields=["parish"], name="meta_inform_parish_50ef38_idx"),
        ),
        migrations.AddIndex(
            model_name="metainformation",
            index=models.Index(fields=["municipality"], name="meta_inform_municip_648f7d_idx"),
        ),
        migrations.AddIndex(
            model_name="metainformation",
            index=models.Index(fields=["current_location"], name="meta_inform_current_c541cc_idx"),
        ),
        migrations.AddIndex(
            model_name="metainformation",
            index=models.Index(fields=["style"], name="meta_inform_style_e7d9eb_idx"),
        ),
    ]
