# Generated by Django 5.0 on 2024-01-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metainformation",
            name="year_from",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metainformation",
            name="year_to",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TranslationSwedish",
            fields=[
                ("value", models.TextField(blank=True)),
                ("search_value", models.TextField(blank=True)),
                (
                    "signature",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="translation_swedish",
                        serialize=False,
                        to="runes.signature",
                    ),
                ),
            ],
            options={
                "db_table": "translation_swedish",
                "indexes": [models.Index(fields=["search_value"], name="translation_search__1eac6a_idx")],
            },
        ),
    ]
