# Generated by Django 5.2.7 on 2026-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runes", "0002_metainformation_year_from_metainformation_year_to_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaWithCrossesTextual",
            fields=[
                ("meta_id", models.IntegerField(primary_key=True, serialize=False)),
                ("crosses_textual", models.TextField()),
            ],
            options={
                "db_table": "meta_with_crosses_textual",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1500, unique=True)),
            ],
            options={
                "db_table": "references",
                "ordering": ["text"],
            },
        ),
        migrations.AddField(
            model_name="metainformation",
            name="references",
            field=models.ManyToManyField(blank=True, related_name="meta_informations", to="runes.reference"),
        ),
    ]
