name: Pull Request Checks

on:
  pull_request:
    branches:
      - master

jobs:
  call-npm-test:
    name: NPM Test
    uses: ./.github/workflows/npm-test-template.yml

  call-python-test:
    name: Python Test
    uses: ./.github/workflows/python-test-template.yml
